services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www
      - ./storage/database:/var/www/storage/database # SQLiteファイル用
    environment:
      # Xdebug設定（開発環境）
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      # MySQL接続設定
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: stamp_master
      MYSQL_USERNAME: stamp_user
      MYSQL_PASSWORD: stamp_pass
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - stamp-network

  web:
    image: nginx:alpine
    ports:
      - "0.0.0.0:18088:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - stamp-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: stamp_master
      MYSQL_USER: stamp_user
      MYSQL_PASSWORD: stamp_pass
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "0.0.0.0:13307:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - stamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: stamp_user
      PMA_PASSWORD: stamp_pass
    ports:
      - "0.0.0.0:18081:80"
    depends_on:
      - mysql
    networks:
      - stamp-network

  # Node.js for Vite development server
  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      VITE_HOST: 0.0.0.0
      VITE_PORT: 5173
      VITE_HMR_HOST: localhost
      VITE_HMR_PORT: 15173
    ports:
      - "0.0.0.0:15173:5173"
    command: sh -c "npm install && npm run dev"
    env_file:
      - .env
    networks:
      - stamp-network

volumes:
  mysql_data:

networks:
  stamp-network:
    driver: bridge